export const cities = [
	"azua",
	"bani",
	"barahona",
	"boca-chica",
	"boca-de-yuma",
	"bonao",
	"cabarete",
	"comendador",
	"constanza",
	"cotui",
	"dajabon",
	"duverge",
	"el-seibo",
	"higuey",
	"jarabacoa",
	"jimani",
	"la-romana",
	"las-terrenas",
	"la-vega",
	"mao",
	"miches",
	"moca",
	"monte-cristi",
	"monte-plata",
	"nagua",
	"neiba",
	"palmar-de-ocoa",
	"pedernales",
	"puerto-plata",
	"punta-cana",
	"sabana-de-la-mar",
	"santiago-rodriguez",
	"salcedo",
	"samana",
	"san-cristobal",
	"san-francisco-de-macoris",
	"san-jose-de-ocoa",
	"san-juan",
	"san-pedro-de-macoris",
	"santiago",
	"santo-domingo",
	"sosua",
] as const;

export type Cities = (typeof cities)[number];
